language: python
python:
  - '3.8'

branches:
  only:
    - staging

env: DJANGO_SETTINGS_MODULE="P10.settings"

services:
  - postgresql

before_script:
  - pip install -r requirements.txt
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - ./manage.py test