language: python
python:
  - '3.8'

branches:
  only:
    - staging

env: DJANGO_SETTINGS_MODULE="settings.travis"

services:
  - postgresql

before_script:
  - pip install -r requirements.txt
  - psql -c 'create database travis_ci_test;' -U postgres
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - python manage.py test