language: python
python:
  - '3.8'

branches:
  only:
    - staging
  
addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12

env:
- DJANGO_SETTINGS_MODULE="settings.travis"
  global:
    - PGPORT=5433
    - PGUSER=travis

services:
  - postgresql

before_script:
  - pip install -r requirements.txt
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - python manage.py test