language: python
python:
  - '3.8'

branches:
  only:
    - staging
  
addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12

env: DJANGO_SETTINGS_MODULE="settings.travis"

services:
  - postgresql

before_script:
  - pip install -r requirements.txt

script:
  - python manage.py test
