language: python
python:
  - '3.8'

branches:
  only:
    - travisstaging

services:
  - postgresql

addons:
  chrome: stable
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5432
  - PGUSER=postgres

before-install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=8000 http://localhost &
  ⋮

before_script:
  - psql -c 'CREATE DATABASE travis_db_test;' -U postgres

script:
  - python3 manage.py migrate
  - python3 manage.py test